language: python
python:
  - "3.3"
install: 
  - pip install -r requirements.txt --use-mirrors
script: nosetests
virtualenv:
  system_site_packages: true
before_install:
  - pip install numpy
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran python3-dateutil python3-six 
  - sudo apt-get install -qq python3-scipy 
notifications: 
  email: false
